/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.*;
import javax.swing.*;




/**
 *
 * @author Dell
 */
public class frmIndex extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    
    public frmIndex() {
        initComponents();
        this.setContentPane(fondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuSocios = new javax.swing.JMenuItem();
        menuPeliculas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuPrecios = new javax.swing.JMenuItem();
        menuMovimientos = new javax.swing.JMenu();
        menuAlquiler = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido");
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jMenuBar1.setForeground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(500, 50));

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/iconoArchivos.png"))); // NOI18N
        menuArchivo.setText("Archivos");

        menuSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/iconoSocios.png"))); // NOI18N
        menuSocios.setText("Socios");
        menuSocios.setPreferredSize(new java.awt.Dimension(200, 40));
        menuSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSociosActionPerformed(evt);
            }
        });
        menuArchivo.add(menuSocios);

        menuPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/iconoPeliculas.png"))); // NOI18N
        menuPeliculas.setText("Peliculas");
        menuPeliculas.setPreferredSize(new java.awt.Dimension(200, 40));
        menuPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPeliculasActionPerformed(evt);
            }
        });
        menuArchivo.add(menuPeliculas);
        menuArchivo.add(jSeparator1);

        menuPrecios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/iconoPrecios.png"))); // NOI18N
        menuPrecios.setText("Precios");
        menuPrecios.setPreferredSize(new java.awt.Dimension(200, 40));
        menuPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPreciosActionPerformed(evt);
            }
        });
        menuArchivo.add(menuPrecios);

        jMenuBar1.add(menuArchivo);

        menuMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/iconoMovimientos.png"))); // NOI18N
        menuMovimientos.setText("Movimientos");

        menuAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/iconoAlquiler.png"))); // NOI18N
        menuAlquiler.setText("Alquiler");
        menuAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlquilerActionPerformed(evt);
            }
        });
        menuMovimientos.add(menuAlquiler);

        jMenuBar1.add(menuMovimientos);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/iconoAyuda.png"))); // NOI18N
        jMenu1.setText("Ayuda");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSociosActionPerformed
        frmSocios Socio = new frmSocios();
        Socio.setVisible(true);
    }//GEN-LAST:event_menuSociosActionPerformed

    private void menuPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPeliculasActionPerformed
        frmPelicula frmPelicula = new frmPelicula();
        frmPelicula.setVisible(true);
    }//GEN-LAST:event_menuPeliculasActionPerformed

    private void menuPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPreciosActionPerformed
        frmPrecios frmPrecios = new frmPrecios();
        frmPrecios.setVisible(true);
    }//GEN-LAST:event_menuPreciosActionPerformed

    private void menuAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlquilerActionPerformed
        frmAlquiler frmAlquiler = new frmAlquiler();
        frmAlquiler.setVisible(true);
    }//GEN-LAST:event_menuAlquilerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuAlquiler;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenuItem menuPeliculas;
    private javax.swing.JMenuItem menuPrecios;
    private javax.swing.JMenuItem menuSocios;
    // End of variables declaration//GEN-END:variables

//Imagen de fondo
    class FondoPanel extends JPanel
    {
        private Image imagen;
        
      @Override
      public void paint(Graphics g)
      {
          imagen = new ImageIcon(getClass().getResource("/imagenes/fondoIndex.png")).getImage();
          
          g.drawImage(imagen, 0, 0, getWidth(),getHeight(),this);
          
          setOpaque(false);
          
          super.paint(g);
      }
        }

    
  //Icono


    @Override
    public Image getIconImage() {
   Image retValue = Toolkit.getDefaultToolkit().
         getImage(ClassLoader.getSystemResource("Imagenes/Iconos/iconoIndex.png"));

   return retValue;
}
    
    



}
